/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.REACT_APP_AWS_PROJECT_REGION,
    "aws_cognito_identity_pool_id": '',
    "aws_user_pools_id": process.env.REACT_APP_AWS_USER_POOLS_ID,
    "aws_user_pools_web_client_id": process.env.REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID,
};

// const awsmobile = {
//     "aws_project_region": 'ap-northeast-2',
//     "aws_cognito_identity_pool_id": '',
//     "aws_user_pools_id": 'ap-northeast-2_qCjWAmKqw',
//     "aws_user_pools_web_client_id": '2lps1llva1t5bkbe5g16qbb2cs',
// };


export default awsmobile;
